### ISSUE TITLE
SMV won't run on OSX 10.5 (Leopard). Possible linking issue.

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#1052]
```
Application Version: SMV 5.5.4
SVN Revision Number: 6130
Compile Date: Apr 26 2010
Operating System: OSX 10.5 (Leopard)

The latest versions of Smokeview do not work on OSX 10.5, and result in the following
error:

-----

**Running Smokeview File: 
/Users/Craig/Desktop/Thermocouple_1mm_new/tc_test/vertical_plates_diameter1mm_new.smv

**
dyld: lazy symbol binding failed: Symbol not found: _fopen$UNIX2003
 Referenced from: /Applications/FDS/FDS5/bin/smv5_osx_32
 Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _fopen$UNIX2003
 Referenced from: /Applications/FDS/FDS5/bin/smv5_osx_32
 Expected in: /usr/lib/libSystem.B.dylib

sh: line 1:   780 Trace/BPT trap          /Applications/FDS/FDS5/bin/smv5_osx_32 
vertical_plates_diameter1mm_new > vertical_plates_diameter1mm_new.log

-----

... which appears to be a linking issue for running applications on OSX 10.5 that were
compiled 
on OSX 10.6.

Version 5.4.6 of SMV works, presumably since it was the last version that was compiled
on OSX 
10.5. And since users may still be using 10.5, is there a way to statically build SMV
so that it 
will work?
```

Original issue reported on code.google.com by `koverholt` on 2010-05-03 20:20:28

**Comment by gforney** [comment]
```
I'll take a look at it.
```

Original issue reported on code.google.com by `gforney` on 2010-05-04 11:34:06

**Comment by gforney** [comment]
```
It works on my 10.5 system.  Try typing just smv5_osx_2 -v from a command line.
```

Original issue reported on code.google.com by `gforney` on 2010-05-05 14:54:06

**Comment by gforney** [comment]
```
Just tried it on 10.5 with the command you gave and it prints out the version successfully.
However, when I try 
to open any SMV case I get the same error message as above.
```

Original issue reported on code.google.com by `koverholt` on 2010-05-05 16:59:46

**Comment by gforney** [comment]
```
the the test smokeview I just posted at
http://code.google.com/p/fds-smv/downloads/detail?name=smv554_osx_32_static&can=2&q=#makechanges
```

Original issue reported on code.google.com by `gforney` on 2010-05-05 17:11:50

**Comment by gforney** [comment]
```
Try the test smokeview I just posted at
http://code.google.com/p/fds-smv/downloads/detail?name=smv554_osx_32_static&can=2&q=#makechanges
```

Original issue reported on code.google.com by `gforney` on 2010-05-05 17:12:21

**Comment by gforney** [comment]
```
Tried the test SMV just posted, same error.
```

Original issue reported on code.google.com by `koverholt` on 2010-05-05 17:59:11

**Comment by gforney** [comment]
```
I'm also searching for similar Mac issues now, I'll let you know if I find any useful
compiler flags that might 
solve the problem.
```

Original issue reported on code.google.com by `koverholt` on 2010-05-05 18:18:10

**Comment by gforney** [comment]
```
I found a mention of this ifort flag:

-mmacosx-version-min=10.5

which should allow SMV to be backwards compatible to OSX 10.5 by taking into account
symbol variations. -
mmacosx-version-min=10.4 is also available, but 10.5 has been out since 2007 and it
might be too much of 
a pain to support back to 10.4.
```

Original issue reported on code.google.com by `koverholt` on 2010-05-05 18:31:26

**Comment by gforney** [comment]
```
I'm already using -mmacosx-version-min=10.4
```

Original issue reported on code.google.com by `gforney` on 2010-05-05 19:03:40

**Comment by gforney** [comment]
```
do you get the same problem when you run the 64 bit smokeview?
```

Original issue reported on code.google.com by `gforney` on 2010-05-05 19:46:05

**Comment by gforney** [comment]
```
Excellent, didn't think of trying that. 64 bit SMV works fine on 10.5 with no errors.
So this would mean a 
problem for 32 bit machines that are > 4 years old running 10.5 or older, which are
probably very few people 
if any at all that are running SMV.

Issue has been verified. Thanks for your help on this, Glenn.
```

Original issue reported on code.google.com by `koverholt` on 2010-05-05 20:55:57

**Comment by gforney** [comment]
```
I think that if the Mac in question is running a 32 bit OS then the 32 bit smokeview

will work and the 64 bit won't.  In any case, we can cross that bridge when we get

to it.
```

Original issue reported on code.google.com by `gforney` on 2010-05-06 01:58:20

**Comment by gforney** [comment]
```
Hello! I have this same problem. I'm trying to run smokeview for the very first time.
My mac is from 2007 and I'm currently running os x 10.5.8. Where can I find this "-mmacosx-version-min=10.4"
and how can I fix this?
```

Original issue reported on code.google.com by `timo.oikkonen` on 2011-02-25 21:22:52

**Comment by gforney** [comment]
```
That's a compiler flag if you are compiling SMV yourself. Did you try both 32 and 64
bit versions of SMV?
```

Original issue reported on code.google.com by `koverholt` on 2011-02-26 00:39:15

**Comment by gforney** [comment]
```
The only solution I can offer is to upgrade your mac to a current OS.  I never got the
-mmacosx-version-min=10.4 (or 10.5) option to work as intended.
```

Original issue reported on code.google.com by `gforney` on 2011-02-26 16:11:25

**Comment by gforney** [comment]
```
One last try.  I re-built smokeview 5.6.3 (r7457) adding the -mmacosx-version-min=10.4
to the compile options (in addition to the link options).  Note this is the same revision
as the latest released version.

Copy the two smokeview's in the following compressed tar file into your bin directory.
 Let me know what happens when you try to run them.

http://code.google.com/p/fds-smv/downloads/detail?name=smv_5.6.3a_osx.tar.gz&can=2&q=#makechanges
```

Original issue reported on code.google.com by `gforney` on 2011-02-26 16:51:27

**Comment by gforney** [comment]
```
I'm closing this case.  If youtry out the new smokeview's I built and report back I
will take a look at it.
```

Original issue reported on code.google.com by `gforney` on 2011-03-06 22:52:51
