### ISSUE TITLE
Can´t find FDS and Smokeview to work with OS X 10.5.8

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#1298]
```
Application Version: 5.5.3
SVN Revision Number: ?
Compile Date: ?
Operating System: OS X 10.5.8


I´m having problem with FDS and Smokeview on my MAC. I downloaded the FDS_5.5.3-SMV_5.6_osx_32.tar.gz
bundle but it don´t seem to work. When I try to launch a .fds file in the launcher
I only get this:

*** Input archive file: test.zip 

 *** Running Input File: test.fds

 Fire Dynamics Simulator

 Compilation Date : Fri, 29 Oct 2010

 Version: 5.5.3; MPI Disabled; OpenMP Disabled
 SVN Revision No. : 7031

 Job TITLE        : TEST
 Job ID string    : test

dyld: lazy symbol binding failed: Symbol not found: _fopen$UNIX2003
  Referenced from: /Applications/FDS/FDS5/bin/fds5_osx_32
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _fopen$UNIX2003
  Referenced from: /Applications/FDS/FDS5/bin/fds5_osx_32
  Expected in: /usr/lib/libSystem.B.dylib

It creates a folder with the .smv file but when I run that one I recieve this:


 FDS-SMV Launcher for OSX
 **** Version: 1.2.1 ****

***Running Smokeview File: /Users/johannilsen/Desktop/test/test.smv ***
dyld: unknown required load command 0x80000022
sh: line 1:  1769 Trace/BPT trap          /Applications/FDS/FDS5/bin/smv5_osx_32 test
> test.log


I have read about similar problems in other issues and I have tried to follow the advices
but I can´t manage to get it right. Does anyone have an idea how to get it right?

Thanks in advance
```

Original issue reported on code.google.com by `gbr08jni@student.lu.se` on 2011-02-08 20:34:16

**Comment by gforney** [comment]
```
Randy, have you ever tried to install FDS on your Mac? Could you try it and see if we
can reproduce this error.
```

Original issue reported on code.google.com by `mcgratta` on 2011-02-08 20:45:06

**Comment by gforney** [comment]
```
Try running the 64_bit version instead of the 32_bit.
Test from the command line first, then try with the launcher.

If the 64-bit version is installed, the Launcher should use it instead of the 32_bit
version.

Same thing with Smokeview.
```

Original issue reported on code.google.com by `bryanwklein.teci` on 2011-02-08 20:59:21

**Comment by gforney** [comment]
```
Kevin,
Most recent release of FDS and Smokeview are working great on my iMac here.

```

Original issue reported on code.google.com by `bryanwklein.teci` on 2011-02-08 21:00:25

**Comment by gforney** [comment]
```
Yes, I've had no problems running either FDS or SMV on my Macs.
```

Original issue reported on code.google.com by `randy.mcdermott` on 2011-02-08 21:08:20

**Comment by gforney** [comment]
```
I don't run with the launcher, though.  Just open a terminal, cd to the input file directory
and run FDS from the command line:

>/Applications/FDS/FDS5/bin/fds5_osx_32 filename.fds

Run smokeview by

>/Applicaitons/FDS/FDS5/bin/smv5_osx_32 filename

I also set up alias in my ~/.bash_profile

Open a terminal.  Type

vi .bash_profile

Add the following

alias fds="/Applications/FDS/FDS5/bin/fds5_osx_32"
alias smv="/Applications/FDS/FDS5/bin/smv5_osx_32"

Hit Escape, then :wq to save and quit.  Close the terminal and open a new one.  Now
you can just type

fds chid.fds

and

smv chid

To run the programs.

```

Original issue reported on code.google.com by `randy.mcdermott` on 2011-02-08 21:17:01

**Comment by gforney** [comment]
```
To the person who originally posted the problem. Could you see if you can just run the
executable of FDS and Smokeview at the command line. 
```

Original issue reported on code.google.com by `mcgratta` on 2011-02-08 21:46:26

**Comment by gforney** [comment]
```
Thanks for the answers!

I have now tried to run it through the terminal, still on the 32_bit. There is no problem
getting to the bin-folder but when I type /fds5_osx_32 it says"not a directory". So
I´m stuck there aswell.

To the previous post: I´m sorry but I´m not that skilled at this, what exactly do you
mean by "run the executable"?
```

Original issue reported on code.google.com by `gbr08jni@student.lu.se` on 2011-02-09 06:33:00

**Comment by gforney** [comment]
```
I now downloaded the FDS_5.5.3a-SMV_5.6_osx_64.tar.gz bundle but I still have problem.
When I try going through the terminal I get the same problem, "not a directory". When
I tried it through the launcher I didn´t recieve the same error as with the 32_bit,
instead I got this:



 FDS-SMV Launcher for OSX
 **** Version: 1.2.1 ****

 *** Input archive file: room_fire.zip 

 *** Running Input File: room_fire.fds
dyld: unknown required load command 0x80000022

I creates a folder but it only contains a .zip file. Thoughts anybody? 
```

Original issue reported on code.google.com by `gbr08jni@student.lu.se` on 2011-02-09 06:57:27

**Comment by gforney** [comment]
```
Hi.  Once you get to the correct directory, you have to type

>.fds5_osx_32

Note the period before the executable.  When you type /fds5_osx_32, you are asking
to run from the root.

Alternatively, try

~/FDS/FDS5/bin/fds5_osx_32


```

Original issue reported on code.google.com by `randy.mcdermott` on 2011-02-09 13:05:09

**Comment by gforney** [comment]
```
Sorry, I was slightly off.  Once in the bin directory, type ./fds5_osx_32.  Like this:


molly:~ randy$ cd /Applications/FDS/FDS5/bin/
molly:bin randy$ ls
FDS-SMV_5_OSX_Launcher.app.zip  fds5_mpi_osx_64         smokeview.ini
README_OSX.html         fds5_osx_64         smokezip_osx_64
RELEASE_INFO.txt        objects.svo         smv5_osx_64
fds2ascii_osx_64        smokediff_osx_64        textures
molly:bin randy$ ./fds5_osx_64 

Fire Dynamics Simulator

Version: 5.5.3; MPI Disabled; OpenMP Disabled
SVN Revision Number: 7031
Compile Date: Fri, 29 Oct 2010

Consult FDS Users Guide Chapter, Running FDS, for further instructions.

Hit Enter to Escape...

```

Original issue reported on code.google.com by `randy.mcdermott` on 2011-02-09 13:27:43

**Comment by gforney** [comment]
```
Now, assuming the executable works, if you want to run FDS anywhere on your system,
type

/Applications/FDS/FDS5/bin/fds5_osx_64 input_file.fds

where input_file.fds is the name of the input file. Someone who knows unix can help
set up an alias for the path. Tell us if this works for you.

```

Original issue reported on code.google.com by `mcgratta` on 2011-02-09 14:03:54

**Comment by gforney** [comment]
```
Thanks agains for helping me but it still doesn´t work.

 When I open a file through the terminal, as mentioned above, I recieve the same error
as before.  With the 64_bit I can´t even reach to the program. When I type ./fds5_osx_64
in the .bin directory I get this

dyld: unknown required load command 0x80000022
Trace/BPT trap

When I use the 32_ bit I get 

Macintosh-5:bin johannilsen$ ./fds5_osx_32 test.fds

 Fire Dynamics Simulator

 Compilation Date : Fri, 29 Oct 2010

 Version: 5.5.3; MPI Disabled; OpenMP Disabled
 SVN Revision No. : 7031

 Job TITLE        : TEST
 Job ID string    : test

dyld: lazy symbol binding failed: Symbol not found: _fopen$UNIX2003
  Referenced from: /Applications/FDS/FDS5/bin/./fds5_osx_32
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _fopen$UNIX2003
  Referenced from: /Applications/FDS/FDS5/bin/./fds5_osx_32
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap

So I´m still having problem. I assume it´s because I use 10.5.8 and not 10.6, but there
must be some way to make it work anyway, I saw on the download site that there is a
version, FDS_5.5.0b-SMV_5.5.3b_osx_32.tar.gz, with apps re-linked with option to make
them compatible with older versions of OSX. I tried it once and it didn´t work but
maybe I did something wrong. Do you think it can help?


```

Original issue reported on code.google.com by `gbr08jni@student.lu.se` on 2011-02-09 16:44:10

**Comment by gforney** [comment]
```
I don't think it is OS X.

Did you try just opening a terminal and typing

/Applications/FDS/FDS5/bin/fds5_osx_32 test.fds

??
```

Original issue reported on code.google.com by `randy.mcdermott` on 2011-02-09 16:53:22

**Comment by gforney** [comment]
```
Yes I tried that, same thing happends.
```

Original issue reported on code.google.com by `gbr08jni@student.lu.se` on 2011-02-09 18:22:22

**Comment by gforney** [comment]
```
In general, we don't support older versions of OSX. It has become a real problem for
us to do this. I can only suggest that you upgrade to the latest version of OSX. If
the executable simply does not run as you have shown, we cannot fix this problem.
```

Original issue reported on code.google.com by `mcgratta` on 2011-02-09 18:33:50

**Comment by gforney** [comment]
```
Okey that's too bad. But thanks all of you for helping, really appreciate it.
```

Original issue reported on code.google.com by `gbr08jni@student.lu.se` on 2011-02-09 19:09:18

**Comment by gforney** [comment]
```
We'll close the issue for now. However, if you upgrade your OS and still have problems,
re-open the issue.
```

Original issue reported on code.google.com by `mcgratta` on 2011-02-09 19:37:23
