### ISSUE TITLE
Compiling fds on Ubuntu 20.04 reports an error.

### ISSUE THREAD

**Issue by ZQJ269** [firemodels/fds#9995]
hello,

I'm trying to compile fds on Ubuntu 20.04 using gfortran. i followed the tutorial given on the wiki. the Ubuntu system given on the wiki is 18.04. before this, i was able to compile on 16.04. But when I compiled on 20.04, I got an error as follows：

mpifort -O3 -cpp -DGITHASH_PP=\"-HEAD\" -DGITDATE_PP=\""\"" -DBUILDDATE_PP=\""Oct 30, 2021  22:16:52\"" -DCOMPVER_PP=\"\" -fopenmp -o fds_mpi_gnu_linux_64 prec.o cons.o devc.o data.o type.o mesh.o func.o smvv.o irad.o turb.o soot.o ieva.o pois.o scrc.o radi.o evac.o gsmv.o geom.o part.o vege.o ctrl.o samr.o dump.o hvac.o mass.o read.o wall.o fire.o divg.o velo.o pres.o init.o main.o
/usr/bin/ld: /shared/openmpi_64/lib/libopen-pal.a(reachable_netlink_utils_common.o): undefined reference to symbol 'nlmsg_set_proto'
/usr/bin/ld: /lib/x86_64-linux-gnu/libnl-3.so.200: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [../makefile:319: mpi_gnu_linux_64] Error 1

I have searched the web for solutions, but they don't work. I don't know what's wrong, is Ubuntu 20.04 unable to compile fds, it seems I'm the first one to encounter this problem, does anyone know what's going on?

**Comment by mcgratta** [comment]
I have no advice to offer other than try an Internet search on the error message. At NIST, we use the Intel oneAPI Fortran compiler and MPI libraries. These are now free, and work well for us. I do not see anything in the error message that is related to something specific within FDS.

**Comment by gforney** [comment]
Where did you get the openmpi library? Purely a guess, i wonder if it is
compatible with your version of the OS

**Comment by mcgratta** [comment]
@CFDzhou -- have you made any progress on this issue? We cannot reproduce it on our cluster. We use Centos, not Ubuntu.

**Comment by ZQJ269** [comment]
> @CFDzhou -- have you made any progress on this issue? We cannot reproduce it on our cluster. We use Centos, not Ubuntu.

Thank you, Kevin. I have solved the problem and I found out that it was because there was a problem with the dynamic library connection between the old and new versions. I downloaded the old dynamic libraries and replaced them with the new Ubuntu version and the problem was solved.By the way, I was doing fds calculation and called 16 core parallel calculation and I found that the program reported an error and showed the following：

#Backtrace for this error:
#Program received signal SIGSEGV: Segmentation fault - invalid memory reference

My server is configured with 64 cores and 128G of RAM。I'm wondering if I don't have enough memory, but it shouldn't be like this。Anyway, I appreciate your reply! Thank you again!

**Comment by mcgratta** [comment]
Thanks for letting me know.
