### ISSUE TITLE
compilation probles of FDS with OpenSuse 10.3 (x64)

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#372]
```
Application Version: 5.2.0
SVN Revision Number: 1904
Compile Date: 26.06.2008
Operating System: OpenSuse 10.3 (x64)

Describe details of the issue below:

compile with gcc (gcc version 4.2.1 (SUSE Linux)) and gfortran ends with 

------------------------------------------------------------------
dump.o: In function `__dump__initialize_mesh_dumps':
dump.f90:(.text+0x7a3c): undefined reference to `isoheader_'
dump.f90:(.text+0x7bcb): undefined reference to `tisoheader_'
dump.f90:(.text+0x8175): undefined reference to `smoke3dheader_'
dump.f90:(.text+0x8709): undefined reference to `smoke3dheader_'
dump.o: In function `__dump__dump_isof':
dump.f90:(.text+0x32f46): undefined reference to `iso2file_'
dump.f90:(.text+0x338f0): undefined reference to `isot2file_'
dump.o: In function `__dump__dump_smoke3d':
dump.f90:(.text+0x3445a): undefined reference to `smoke3dtofile_'
collect2: ld returned 1 exit status
make: *** [gnu_32] Fehler 1
------------------------------------------------------------------

After modification of the CFLAGS for the corresponding section (deleting
"-D pp_noappend" compiling worked:

gnu_32 : CFLAGS  = -O1

Cornelius Schönnenbeck

P.S. compiler optimization O3 was fastes

```

Original issue reported on code.google.com by `c.schoenne` on 2008-06-27 10:57:34

**Comment by gforney** [comment]
```
Thanks for the information. Is there a question or problem? If not, in the future it

would be better to post this to the Discussion Group, but not as a new post, but 
rather as a follow-up to an on-going discussion about "pp_noappend" or "compiling"

or "gnu_32". Then, if someone searches on these keywords, they can learn what you 
have done that worked.
```

Original issue reported on code.google.com by `mcgratta` on 2008-06-27 11:59:05

**Comment by gforney** [comment]
```
I am closing this case, but it will remain searchable so that the information is 
available to others.
```

Original issue reported on code.google.com by `mcgratta` on 2008-07-07 19:38:58
